language: python
deploy:
  provider: heroku
  api_key:
    secure: kVkfbqtfuPle6/afNjtyJGHB2yuFRRgpHTenFCP+47PRG5QBnCYmmVWhEO17d4afgr876oY0GJmj5awYU1jbvQFTfp+4wgpzIgTUHS5TQ29pXU3D4XKlYqQ6Taz6WtrBwIjD8IUBnwoXy+QhoyIB2CSnzwdLtf5LPIA9JrJAdBQnEKYqjWeD4oBx/6bDEBv1kfsoENmN8VHMQyFLB5cN8OJVtlP7aPcfgygz6ziqxvn8OwusRGOB975uElWhA+anJ2Z16jbTxypCpkffnzSlf+JKH9xqDwQDtaKDBDgZPaFd9qrVrtlgbV8TQXNnbxuBI9jR+hS/uVFaZVd19BUG7sYbhoHtR0lGjx6bStDjLGZnau53Cg9kMGR4aBtaB4Q8PjXUkAvu7o5aDU/HKaGg8jVE/mWIk9D7wVgGJYyGW5zVvCrWBxnMyxxB0f99v9xH35rh+4u5eEdaw4sfFhzdYmSfsxioNREzX76wWpCUx4S64QTGS1a5u868yhnvl1L7eI2muOE741AcJZKrMKEaHfI+ACWwbWRj3CH3cimI/rgEORC6MylFt324enzyyEf9x5f2XXGfqBbyrqtkQgm58dhFDb7Kpg9hqUbkIJGO7KYuMTsFe+6nzRr9vl7YDaSGGOfozo9EuDqjWvEl1jmBP754irx31Pz+9d/Iwvs8G70=
  app:
    master: copm307p1-staging
